# Site settings
title: jeqo's blog
email: quilcate.jorge@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  About java, oracle fusion middleware, devops, poc, and more
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jeqo89
github_username:  jeqo
highlighter: pygments

# Build settings
markdown: kramdown
